In [1]:
import pandas as pd

In [61]:
f1 = pd.read_csv('open_library_x_nyt_0_615.csv')
f2 = pd.read_csv('open_library_x_nyt_2.csv')
f3 = pd.read_csv('open_library_x_nyt.csv')
f4 = pd.read_csv('open_library_x_nyt_polina.csv')
f5 = pd.read_csv('open_library_x_nyt_katya.csv')
f6 = pd.read_csv('open_library_x_nyt_eugene.csv') 
f7 = pd.read_csv('open_library_x_nyt_eugene_2.csv')

In [62]:
df = pd.concat(
    [f1, f2, f3, f4, f5, f6, f7],
    ignore_index=True
)
df

,Unnamed: 0,age_group,amazon_product_url,article_chapter_link,asterisk,author,book_image,book_image_height,book_image_width,book_review_link,...,sunday_review_link,title,updated_date,weeks_on_list,isbns,buy_links,avg_rating,rating_count,title_open_library,author_open_library
0,0,NaN,https://www.amazon.com/dp/1638932239?tag=thene...,NaN,0,Navessa Allen,https://static01.nyt.com/bestsellers/images/97...,400,312,NaN,...,NaN,LIGHTS OUT,2026-04-03T16:35:10.385Z,8,"[{'isbn10': '', 'isbn13': '9781638932239'}]","[{'name': 'Amazon', 'url': 'https://www.amazon...",4.409091,22.0,Lights Out,['Navessa Allen']
1,1,NaN,https://www.amazon.com/dp/0804190119?tag=thene...,NaN,0,Timothy Snyder,NaN,0,0,NaN,...,NaN,ON TYRANNY,2026-04-02T01:29:16.596Z,39,"[{'isbn10': '', 'isbn13': '9780804190114'}]","[{'name': 'Amazon', 'url': 'https://www.amazon...",4.142857,28.0,On Tyranny,"['Timothy Snyder', 'Núria Parés Sellarés']"
2,2,NaN,https://www.amazon.com/dp/0593820282?tag=thene...,NaN,0,Matt Dinniman,https://static01.nyt.com/bestsellers/images/97...,500,331,NaN,...,NaN,THE DUNGEON ANARCHIST'S COOKBOOK,2026-04-02T00:03:06.944Z,3,"[{'isbn10': '', 'isbn13': '9783748087342'}]","[{'name': 'Amazon', 'url': 'https://www.amazon...",4.500000,2.0,The Dungeon Anarchist’s Cookbook,['Matt Dinniman']
3,3,NaN,https://www.amazon.com/dp/0593820266?tag=thene...,NaN,0,Matt Dinniman,https://static01.nyt.com/bestsellers/images/97...,500,331,NaN,...,NaN,CARL'S DOOMSDAY SCENARIO,2026-04-02T00:02:44.208Z,4,"[{'isbn10': '', 'isbn13': '9783748087335'}]","[{'name': 'Amazon', 'url': 'https://www.amazon...",5.000000,1.0,Carl’s Doomsday Scenario,['Matt Dinniman']
4,4,NaN,https://www.amazon.com/dp/B0F74CH248?tag=thene...,NaN,0,Matt Dinniman,https://static01.nyt.com/bestsellers/images/97...,500,331,NaN,...,NaN,THIS INEVITABLE RUIN,2026-04-02T00:00:43.082Z,2,"[{'isbn10': '', 'isbn13': '9798350430479'}]","[{'name': 'Amazon', 'url': 'https://www.amazon...",5.000000,1.0,This Inevitable Ruin,['Matt Dinniman']
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10978,610,NaN,https://www.amazon.com/dp/0062835777?tag=thene...,NaN,0,V.E. Schwab,https://static01.nyt.com/bestsellers/images/97...,500,383,NaN,...,NaN,GALLANT,2026-03-06T04:50:11.788Z,14,"[{'isbn10': '', 'isbn13': '9780062835772'}]","[{'name': 'Amazon', 'url': 'https://www.amazon...",NaN,NaN,NaN,NaN
10979,611,NaN,https://www.amazon.com/dp/1534488308?tag=thene...,NaN,0,Kelly Yang,https://static01.nyt.com/bestsellers/images/97...,500,331,NaN,...,NaN,NEW FROM HERE,2026-03-06T04:50:02.393Z,4,"[{'isbn10': '', 'isbn13': '9781534488304'}]","[{'name': 'Amazon', 'url': 'https://www.amazon...",NaN,NaN,NaN,NaN
10980,612,NaN,https://www.amazon.com/dp/1982160128?tag=thene...,NaN,0,Stephen Perrine with Heidi Skolnik,https://static01.nyt.com/bestsellers/images/97...,500,331,NaN,...,NaN,THE WHOLE BODY RESET,2026-03-06T04:50:00.193Z,3,"[{'isbn10': '', 'isbn13': '9781982160128'}]","[{'name': 'Amazon', 'url': 'https://www.amazon...",NaN,NaN,NaN,NaN
10981,613,NaN,https://www.amazon.com/dp/1541675649?tag=thene...,NaN,0,Serhii Plokhy,https://static01.nyt.com/bestsellers/images/97...,500,333,NaN,...,NaN,THE GATES OF EUROPE,2026-03-06T04:49:59.16Z,4,"[{'isbn10': '', 'isbn13': '9781541675643'}]","[{'name': 'Amazon', 'url': 'https://www.amazon...",NaN,NaN,NaN,NaN
10982,614,NaN,https://www.amazon.com/dp/1984824341?tag=thene...,NaN,0,Julian Sancton,https://static01.nyt.com/bestsellers/images/97...,500,325,NaN,...,NaN,MADHOUSE AT THE END OF THE EARTH,2026-03-06T04:49:57.888Z,4,"[{'isbn10': '', 'isbn13': '9781984824349'}]","[{'name': 'Amazon', 'url': 'https://www.amazon...",NaN,NaN,NaN,NaN

In [65]:
df_sorted = df.sort_values(by = 'avg_rating')
df_sorted

,Unnamed: 0,age_group,amazon_product_url,article_chapter_link,asterisk,author,book_image,book_image_height,book_image_width,book_review_link,...,sunday_review_link,title,updated_date,weeks_on_list,isbns,buy_links,avg_rating,rating_count,title_open_library,author_open_library
9791,38,NaN,https://www.amazon.com/dp/125031397X?tag=thene...,NaN,0,Aiden Thomas,https://static01.nyt.com/bestsellers/images/97...,500,323,NaN,...,NaN,LOST IN THE NEVER WOODS,2026-03-06T06:19:00.358Z,1,"[{'isbn10': '', 'isbn13': '9781250313973'}]","[{'name': 'Amazon', 'url': 'https://www.amazon...",1.0,1.0,Lost in the Never Woods,"['Aiden Thomas', 'Avi Roque']"
9453,491,NaN,https://www.amazon.com/dp/1464223335?tag=thene...,NaN,0,Ana Huang,https://static01.nyt.com/bestsellers/images/97...,500,324,NaN,...,NaN,THE DEFENDER,2026-03-05T17:47:52.965Z,1,"[{'isbn10': '', 'isbn13': '9781464223334'}]","[{'name': 'Amazon', 'url': 'https://www.amazon...",1.0,1.0,The Defender,['Ana Huang']
62,62,NaN,https://www.amazon.com/dp/059344129X?tag=thene...,NaN,0,Emily Henry,https://static01.nyt.com/bestsellers/images/97...,500,331,NaN,...,NaN,GREAT BIG BEAUTIFUL LIFE,2026-03-18T00:52:24.385Z,0,"[{'isbn10': '', 'isbn13': '9798217063987'}]","[{'name': 'Amazon', 'url': 'https://www.amazon...",1.0,1.0,Great Big Beautiful Life,['Emily Henry']
1981,1366,NaN,https://www.amazon.com/dp/0062937405?tag=thene...,NaN,0,Meena Harris,https://static01.nyt.com/bestsellers/images/97...,500,389,NaN,...,NaN,KAMALA AND MAYA'S BIG IDEA,2026-03-06T06:03:32.289Z,1,"[{'isbn10': '', 'isbn13': '9780062937407'}]","[{'name': 'Amazon', 'url': 'https://www.amazon...",1.0,1.0,Kamala and Maya’s Big Idea,"['Meena Harris', 'Ana Ramírez González']"
2290,1675,NaN,https://www.amazon.com/dp/0063221942?tag=thene...,NaN,0,Jenna Kutcher,https://static01.nyt.com/bestsellers/images/97...,500,331,NaN,...,NaN,"HOW ARE YOU, REALLY?",2026-03-06T05:18:30.124Z,0,"[{'isbn10': '', 'isbn13': '9780063221949'}]","[{'name': 'Amazon', 'url': 'https://www.amazon...",1.0,1.0,"How Are You, Really?",['Jenna Kutcher']
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10978,610,NaN,https://www.amazon.com/dp/0062835777?tag=thene...,NaN,0,V.E. Schwab,https://static01.nyt.com/bestsellers/images/97...,500,383,NaN,...,NaN,GALLANT,2026-03-06T04:50:11.788Z,14,"[{'isbn10': '', 'isbn13': '9780062835772'}]","[{'name': 'Amazon', 'url': 'https://www.amazon...",NaN,NaN,NaN,NaN
10979,611,NaN,https://www.amazon.com/dp/1534488308?tag=thene...,NaN,0,Kelly Yang,https://static01.nyt.com/bestsellers/images/97...,500,331,NaN,...,NaN,NEW FROM HERE,2026-03-06T04:50:02.393Z,4,"[{'isbn10': '', 'isbn13': '9781534488304'}]","[{'name': 'Amazon', 'url': 'https://www.amazon...",NaN,NaN,NaN,NaN
10980,612,NaN,https://www.amazon.com/dp/1982160128?tag=thene...,NaN,0,Stephen Perrine with Heidi Skolnik,https://static01.nyt.com/bestsellers/images/97...,500,331,NaN,...,NaN,THE WHOLE BODY RESET,2026-03-06T04:50:00.193Z,3,"[{'isbn10': '', 'isbn13': '9781982160128'}]","[{'name': 'Amazon', 'url': 'https://www.amazon...",NaN,NaN,NaN,NaN
10981,613,NaN,https://www.amazon.com/dp/1541675649?tag=thene...,NaN,0,Serhii Plokhy,https://static01.nyt.com/bestsellers/images/97...,500,333,NaN,...,NaN,THE GATES OF EUROPE,2026-03-06T04:49:59.16Z,4,"[{'isbn10': '', 'isbn13': '9781541675643'}]","[{'name': 'Amazon', 'url': 'https://www.amazon...",NaN,NaN,NaN,NaN
10982,614,NaN,https://www.amazon.com/dp/1984824341?tag=thene...,NaN,0,Julian Sancton,https://static01.nyt.com/bestsellers/images/97...,500,325,NaN,...,NaN,MADHOUSE AT THE END OF THE EARTH,2026-03-06T04:49:57.888Z,4,"[{'isbn10': '', 'isbn13': '9781984824349'}]","[{'name': 'Amazon', 'url': 'https://www.amazon...",NaN,NaN,NaN,NaN

In [67]:
df_sorted_clean = df_sorted.drop_duplicates(keep = 'first', subset = ['title', 'author'])
df_sorted_clean

,Unnamed: 0,age_group,amazon_product_url,article_chapter_link,asterisk,author,book_image,book_image_height,book_image_width,book_review_link,...,sunday_review_link,title,updated_date,weeks_on_list,isbns,buy_links,avg_rating,rating_count,title_open_library,author_open_library
9791,38,NaN,https://www.amazon.com/dp/125031397X?tag=thene...,NaN,0,Aiden Thomas,https://static01.nyt.com/bestsellers/images/97...,500,323,NaN,...,NaN,LOST IN THE NEVER WOODS,2026-03-06T06:19:00.358Z,1,"[{'isbn10': '', 'isbn13': '9781250313973'}]","[{'name': 'Amazon', 'url': 'https://www.amazon...",1.0,1.0,Lost in the Never Woods,"['Aiden Thomas', 'Avi Roque']"
9453,491,NaN,https://www.amazon.com/dp/1464223335?tag=thene...,NaN,0,Ana Huang,https://static01.nyt.com/bestsellers/images/97...,500,324,NaN,...,NaN,THE DEFENDER,2026-03-05T17:47:52.965Z,1,"[{'isbn10': '', 'isbn13': '9781464223334'}]","[{'name': 'Amazon', 'url': 'https://www.amazon...",1.0,1.0,The Defender,['Ana Huang']
62,62,NaN,https://www.amazon.com/dp/059344129X?tag=thene...,NaN,0,Emily Henry,https://static01.nyt.com/bestsellers/images/97...,500,331,NaN,...,NaN,GREAT BIG BEAUTIFUL LIFE,2026-03-18T00:52:24.385Z,0,"[{'isbn10': '', 'isbn13': '9798217063987'}]","[{'name': 'Amazon', 'url': 'https://www.amazon...",1.0,1.0,Great Big Beautiful Life,['Emily Henry']
1981,1366,NaN,https://www.amazon.com/dp/0062937405?tag=thene...,NaN,0,Meena Harris,https://static01.nyt.com/bestsellers/images/97...,500,389,NaN,...,NaN,KAMALA AND MAYA'S BIG IDEA,2026-03-06T06:03:32.289Z,1,"[{'isbn10': '', 'isbn13': '9780062937407'}]","[{'name': 'Amazon', 'url': 'https://www.amazon...",1.0,1.0,Kamala and Maya’s Big Idea,"['Meena Harris', 'Ana Ramírez González']"
2290,1675,NaN,https://www.amazon.com/dp/0063221942?tag=thene...,NaN,0,Jenna Kutcher,https://static01.nyt.com/bestsellers/images/97...,500,331,NaN,...,NaN,"HOW ARE YOU, REALLY?",2026-03-06T05:18:30.124Z,0,"[{'isbn10': '', 'isbn13': '9780063221949'}]","[{'name': 'Amazon', 'url': 'https://www.amazon...",1.0,1.0,"How Are You, Really?",['Jenna Kutcher']
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4476,3861,NaN,https://www.amazon.com/dp/1338835653?tag=thene...,NaN,0,Ann M. Martin,https://static01.nyt.com/bestsellers/images/97...,0,0,NaN,...,NaN,"JESSI RAMSEY, PET-SITTER",2026-02-24T18:29:07.444Z,3,"[{'isbn10': '', 'isbn13': ''}]","[{'name': 'Amazon', 'url': 'https://www.amazon...",NaN,NaN,NaN,NaN
4477,3862,NaN,https://www.amazon.com/dp/B0DXD7TML1?tag=thene...,NaN,0,Joseph Nguyen,https://static01.nyt.com/bestsellers/images/97...,0,0,NaN,...,NaN,THE OVERTHINKER'S GUIDE TO MAKING DECISIONS,2026-02-24T18:28:49.844Z,2,"[{'isbn10': '', 'isbn13': ''}]","[{'name': 'Amazon', 'url': 'https://www.amazon...",NaN,NaN,NaN,NaN
4478,3863,NaN,https://www.amazon.com/dp/1984855743?tag=thene...,NaN,0,Brené Brown,https://static01.nyt.com/bestsellers/images/97...,0,0,NaN,...,NaN,STRONG GROUND,2026-02-24T18:28:47.35Z,2,"[{'isbn10': '', 'isbn13': ''}]","[{'name': 'Amazon', 'url': 'https://www.amazon...",NaN,NaN,NaN,NaN
4479,3864,NaN,https://www.amazon.com/Kingdom-of-Ash-Sarah-J-...,NaN,0,Sarah J. Maas,NaN,500,500,NaN,...,NaN,KINGDOM OF ASH,2025-10-11T08:18:21.952Z,0,"[{'isbn10': '', 'isbn13': 'DBKADBL022168'}]","[{'name': 'Amazon', 'url': 'https://www.amazon...",NaN,NaN,NaN,NaN
4480,3865,NaN,https://www.amazon.com/dp/B0F5XQQ1YZ?tag=thene...,NaN,0,Takeru Hokazono,https://static01.nyt.com/bestsellers/images/97...,400,312,NaN,...,NaN,"KAGURABACHI, VOL. 4",2025-09-10T13:53:20.368Z,1,"[{'isbn10': '', 'isbn13': '9781974756070'}]","[{'name': 'Amazon', 'url': 'https://www.amazon...",NaN,NaN,NaN,NaN

In [79]:
df_sorted_clean['title_open_library'].isna().sum()

2488

In [71]:
df_sorted_clean.to_csv('final_nyt_clean.csv')